name: React-app CI

on:
  pull_request:
    branches:
      - main
    paths:
      - 'react-app-internal/**'
      - '!react-app-internal/public/**'
      - '!react-app-internal/src/assets/**'

jobs:
  Test:
    name: Vite test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.2'
      - name: Install packages
        run: |
          cd react-app-internal
          npm ci
      - name: Run tests
        run: |
          cd react-app-internal
          npm test