name: Skip tests

on:
  pull_request:
    branches:
      - main
    paths:
      - '**'
      - '!react-app-internal/**'
      - 'react-app-internal/public/**'
      - 'react-app-internal/src/assets/**'

jobs:
  Test:
    name: Vite test
    runs-on: ubuntu-latest
    steps:
      - run: echo test skipped.